services:
  mysql:
    image: mysql:8.0
    container_name: mysql-spring
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: talento
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  mysql-data: